### ISSUE TITLE
swagger-finatra can't work with finatra 2.6.0

### ISSUE THREAD

**Issue by cwwang2** [xiaodongw/swagger-finatra#21]
I'm using Finatra 2.6.0 with swagger-finatra 0.6.0. I got error when compile.
Some part of error message as follow:
======================================================================
[error] missing or invalid dependency detected while loading class file 'SwaggerRouteDSL.class'.
[error] Could not access type AdminIndexInfo in package com.twitter.finatra.http.routing,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'SwaggerRouteDSL.class' was compiled against an incompatible version of com.twitter.finatra.http.routing.
[error] one error found
[error] (compile:compileIncremental) Compilation failed
========================================

Then I find the CHANGLOG at Finatra 2.6.0,  They remove the c.t.finatra.http.routing.AdminIndexInfo
Can't you help this issue?

**Comment by forthy** [comment]
I would like to help this case, but would you please accept [CCW's](https://github.com/xiaodongw/swagger-finatra/pull/19) pull request?

**Comment by forthy** [comment]
I submitted a [pull request](https://github.com/xiaodongw/swagger-finatra/pull/22) that supports Finatra 2.6.0. 
Please review my pull request, thank you very much indeed.
